// murk-css/src/components/button.vue
<script setup lang="ts">
import { ref } from "vue";
defineProps<{ msg: string }>();

const count = ref(0);
</script>

<template>
  <section>
    <h3>Button</h3>
      <button
        class="button button--primary button--small"
        type="button"
        @click="count++"
      >
        <span class="button__text">
          small
          <div class="button__loader"></div>
        </span>
      </button>

      <button
        class="button button--primary button--large"
        type="button"
        @click="count++"
      >
        <span class="button__text">
          Large
          <div class="button__loader"></div>
        </span>
      </button>

      <button
        class="button button--primary button--large button--loading"
        type="button"
        @click="count++"
      >
        <span class="button__text">
          Loading
          <div class="button__loader"></div>
        </span>
      </button>

      <button
        class="button button--primary button--wide"
        type="button"
        @click="count++"
      >
        <span class="button__text">
          Wide
          <div class="button__loader"></div>
        </span>
      </button>

      <button
        class="button button--large button--primary"
        type="button"
        @click="count++"
        disabled
        >
        <span class="button__text">
          Wide
          <div class="button__loader"></div>
        </span>
      </button>
  </section>
</template>

<style scoped>
section {
  max-width: 500px;
  display: grid;
  gap: 1rem;
}
</style>

// murk-react/src/lib/components/button/index.tsx
import { ButtonHTMLAttributes, ReactNode } from "react";

export enum ButtonSizes {
  LARGE = "large",
  WIDE = "wide",
  SMALL = "small",
}

export enum ButtonVariant {
  PRIMARY = "button--primary",
  SECONDARY = "button--secondary",
}

export interface ButtonProps {
  children: ReactNode;
  size?: ButtonSizes;
  variant?: ButtonVariant;
  loading?: boolean;
  disabled?:boolean;
  tag?:"button" | "label" | "span"
}

type NativeProps = ButtonHTMLAttributes<HTMLElement> ;
export const Button = ({
  children,
  size = ButtonSizes.LARGE,
  variant = ButtonVariant.PRIMARY,
  loading,
  className,
  tag = "button",
  ...props
}: ButtonProps & NativeProps) => {
  const Component = tag as any
  return (
    <Component
      className={[
        "button",
        variant,
        loading ? "button--loading" : "",
        `button--${size}`,
        className,
      ].join(" ")}
      {...props}
    >
      <span className="button__text">{children} <div className="button__loader" /></span>
      
    </Component>
  );
};
